config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    # берем либо из сессии, либо из куки
    user_id = request.session[:user_id] || request.cookie_jar.encrypted[:user_id]

    User.find_by(id: user_id)&.admin_role?
  end
end

Rails.application.routes.draw do
  mount Sidekiq::Web =>'/sidekiq', constraints: AdminConstraint.new

  concern :commentable do
    resources :comments, only: %i[create destroy]
  end

  namespace :api do
    resources :tags, only: :index
  end

  # скобки чтобы можно было в маршрут передавать локаль либо не передавать
  # локали передаем из конфига с помощью регулярного выражения
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    # для входа в пользователя в систему, destroy, чтобы пользователь мог выходить
    resource :session, only: %i[new create destroy]

    resource :password_reset, only: %i[new create edit update]

    resources :users, only: %i[new create edit update]

    resources :questions, concern: :commentable do
      resources :answers, except: %i[new show] # except - кроме, т.е. исключаем ненужные маршруты
    end

    resources :answers, except: %i[new show], concern: :commentable

    # создаем пространство имен для admin и маршрут для этого имени
    namespace :admin do
      resources :users, only: %i[index create edit update destroy]
    end

    root 'pages#index'
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include Commentable
  include Authorship

  has_many :answers, dependent: :destroy # если удалить question, то все зависимые ответы тоже долнжы удалиться
  belongs_to :user

  has_many :question_tags, dependent: :destroy
  has_many :tags, through: :question_tags

  validates :title, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 2 }

  # scope - метод класса, который мы можем вызвать(работает как def self.___)
  scope :all_by_tags, lambda { |tag_ids|
    questions = includes(:user, :question_tags, :tags)
    # делаем связку в sql с таблицей тэгов, где tags это tag_ids но только если tag_ids присутствует
    questions = questions.joins(:tags).where(tags: tag_ids) if tag_ids
    questions.order(created_at: :desc)
  }
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  include QuestionsAnswers
  before_action :require_authentication, except: %i[show index]
  before_action :set_question!, only: %i[show destroy edit update]
  before_action :authorize_question!
  # проверяет в экшоне права доступа
  after_action :verify_authorized

  def index
    @tags = Tag.where(id: params[:tags_ids]) if params[:tag_ids]
    # метод pagy возвращает массив из двух элементов. передаем объект, который хотим разбить по страницам
    @pagy, @questions = pagy Question.all_by_tags(@tags)
    @questions = @questions.decorate
  end

  def show
    load_question_answers
  end

  def new
    @question = Question.new
  end

  def edit; end

  def create
    # привязка созданного вопроса к определенному пользователю
    @question = current_user.questions.build question_params
    if @question.save
      respond_to do |format| 
        format.html do 
          flash[:success] = 'Question created!'
          redirect_to questions_path
        end

        format.turbo_stream do 
          @question = @question.decorate
          flash.now[:success] = t('.success')
        end
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @question.update question_params
      flash[:success] = 'Question updated!'
      redirect_to questions_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @question.destroy
    flash[:success] = t('.success')
    redirect_to questions_path
  end

  private

  def question_params
    # запись для tag_ids означает, что для данной позиции идет целый массив из id и каждый id представляет собой тэг
    params.require(:question).permit(:title, :body, tag_ids: [])
  end

  def set_question!
    @question = Question.find params[:id]
  end

  def authorize_question!
    # метод из pundit
    authorize(@question || Question)
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= turbo_frame_tag @question do %>
	<%= form_with model: @question do |f| %>
		<%= render 'shared/errors', object: @question %>

		<div class="mb-3 row">
			<div class="col-sm-2 col-form-label">
				<%= f.label :title %>
			</div>

			<div class="col-sm-10">
				<%= f.text_field :title, placeholder: "Title", class: 'form-control' %>
			</div>
		</div>

		<div class="mb-3 row">
			<div class="col-sm-2 col-form-label">
				<%= f.label :body %>
			</div>

			<div class="col-sm-10">
				<%= f.text_area :body, class: 'form-control' %>
			</div>
		</div>

		<div class="mb-3 row">
			<div class="col-sm-2 col-form-label">
				<%= f.label :tags %>
			</div>

			<div class="col-sm-10">
				<!-- указываем multiple т.к. отображаем много тэгов сразу -->
				<%= f.collection_select :tag_ids, [], :id, :title, {}, multiple: true,
					class: 'js-multiple-select', data: {'ajax-url': '/api/tags'} %>
			</div>
		</div>

		<%= f.submit "Submit question!", class: 'btn btn-primary' %>
	<% end %>
<% end %>

app/views/questions/_question.html.erb
<article class="card my-3">
	<section class="card-header">
		<%= question.user.gravatar %>
		<%= question.user.name_or_email %>
	</section>

	<div class="card-body">
		<h4><%= question.title %></h4>

		<section class="card-text">
			<time datetime="<%= question.formatted_created_at %>">
				<small><%= question.formatted_created_at %></small>		
			</time>

			<div class="my-2">
				<%= render question.tags %>
			</div>

			<p class="my-2">
				<!-- strip_tags - убирает html теги, truncate - ограничивает вывод до определенной длины -->
				<%= truncate strip_tags(question.body), length: 150 %> 
			</p>
		</section>

		<%= link_to 'Show', question_path(question), class: 'btn btn-primary' %> 

		<% if policy(question).edit? %>
			<%= link_to 'Edit', edit_question_path(question), class: 'btn btn-secondary' %> 
		<% end %>

		<% if policy(question).destroy? %>
			<%= link_to t('global.button.delete'), question_path(question), class: 'btn btn-danger',
          data: {turbo_method: :delete, turbo_confirm: t('global.dialog.you_sure')} %>
		<% end %>
	</div>
</article>

app/views/questions/create.turbo_stream.erb
<%= turbo_stream.prepend 'questions', render(@question) %>

app/views/questions/edit.html.erb
<% provide :page_title, 'Edit question' %>
<% currently_at 'Questions' %>

<h1 class="mb-4">Edit question</h1>

<%= render 'form', tags: @tags %>

app/views/questions/index.html.erb
<% provide :page_title, 'Questions' %> <!-- provide передает значение для конкретного yield -->
<% currently_at 'Questions' %>

<h1 class="mb-4">Questions</h1>

<section class="mb-5">
	<h2>Search by tags</h2>

	<%= form_with url: questions_path, method: :get do |f| %>
    <div class="mb-3">
      <%= f.collection_select :tag_ids, (@tags || []), :id, :title, {selected: params[:tag_ids]},
        multiple: true, required: true,
        class: 'js-multiple-select', data: {'ajax-url': '/api/tags'} %>
    </div>

    <%= f.submit t('global.button.submit'), class: 'btn btn-primary' %>

	<% end %>
</section>

<% if policy(:question).new? %>
	<%= link_to 'New question', new_question_path,
		 class: 'btn btn-primary btn-lg mb-3', data: { turbo_frame: dom_id(Question.new) } %>
	
	<div class="my-3">
		<!-- генерируется тэг автоматически на основе dom_id  -->
		<%= turbo_frame_tag Question.new %> 
	</div>
<% end %>

<%== pagination @pagy %>

<%= turbo_frame_tag 'questions' do %>
	<%= render @questions %>
<% end %>

<%== pagination @pagy %>

app/views/questions/new.html.erb
<% provide :page_title, 'New question' %>
<% currently_at 'Questions' %>

<h1 class="mb-4">New question</h1>

<%= render 'form', tags: @tags %>

app/views/questions/show.html.erb
<% provide :page_title, 'Question' %>
<% currently_at 'Questions' %>

<h1 class="mb-4"><%= @question.title %></h1>

<time datetime="<%= @question.formatted_created_at %>">
	<%= @question.formatted_created_at %>		
</time>

<div class="lead my-3">
	<%= sanitize @question.body %>
</div>

<div class="mb-3">
	<%= @question.user.gravatar %>
	<%= @question.user.name_or_email %>
</div>

<%= render 'comments/commentable', commentable: @question, comment: @comment,
	html_id: 'questionComments' %>
 
<% if policy(@question).edit? %>
	<%= link_to 'Edit', edit_question_path(@question), class: 'btn btn-secondary' %> 
<% end %>

<% if policy(@question).destroy? %>
	<%= link_to t('global.button.delete'), question_path(@question), data: {turbo_method: :delete, turbo_confirm: t('global.dialog.you_sure')}, class: 'btn btn-danger mt-3' %>
<% end %>
	

<hr class="my-3">

<h2>Write your answer</h2>

<%= render 'answers/form' %>

<h2 class="mt-4">Answers</h2>

<!-- рендерим паршл, рендерим именно коллекцию @answers, т.е. рендерим поочереди, дальше говорим, как называются элементы коллекции 
 и в локальную переменную question передаем значение глобальной переменной -->
<%= render partial: 'answers/answer', collection: @answers, as: :answer, locals: {question: @question} %>

<%== pagination @pagy %>